version: '3.8'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: mir-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./backend/src:/var/www/laravel_docker
      - ./backend/nginx:/etc/nginx/conf.d
      - ./backend/log:/var/log/nginx
    links:
      - php-fpm
    networks:
      - others_my-net

  php-fpm:
    container_name: mir-php-fpm
    build:
      context: backend/php
    restart: unless-stopped
    ports:
      - "9000:9000"
    working_dir: /var/www/laravel_docker
    volumes:
      - ./backend/src:/var/www/laravel_docker
    networks:
      - others_my-net
      
  mysql:
    image: mysql:8
    container_name: mir_db
    ports:
      - "3306:3306"
    volumes:
      - example-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_base
      MYSQL_PASSWORD: my_base
    networks:
      - others_my-net

  nodejs:
    container_name: mir_node_js
    build:
      context: frontend/src
    ports:
      - 3001:3001
    command: ["npm", "run", "dev"]
    working_dir: /usr/src/app
    volumes:
      - ./frontend/src:/usr/src/app
      - /usr/src/app/node_modules
      
networks:
  others_my-net:
    external: true
    
volumes:
  example-data:


