
export default {
    NAME: 'DIALOGS',

    // SET
    SET_DIALOGS: 'SET_DIALOGS',

    // ACTIONS
    ACTIONS_DIALOGS_CLOSE: "ACTIONS_DIALOGS_CLOSE",
    ACTIONS_DIALOGS_OPEN: "ACTIONS_DIALOGS_OPEN",

    // GET
    GET_DIALOGS: 'GET_DIALOGS',
}